class SecurityConfig:
    SECURITY_PASSWORD_HASH = 'bcrypt'
    SECURITY_PASSWORD_SALT = 'useless'
    SECURITY_TOKEN_AUTHENTICATION_KEY = 'token'

    SECURITY_SEND_REGISTER_EMAIL = False

    SECURITY_REGISTERABLE = True
    SECURITY_RECOVERABLE = True
